apiVersion: v1
kind: Service
metadata:
  name: master
  namespace: locust
  labels:
    app: master
spec:
  selector:
    app: master
  type: LoadBalancer
  ports:
  - port: 8089
    targetPort: 8089

---

apiVersion: v1
kind: Service
metadata:
  name: master-internal
  namespace: locust
  labels:
    app: master
spec:
  selector:
    app: master
  type: ClusterIP
  ports:
  - port: 5557
    targetPort: 5557

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  namespace: locust
  labels:
    app: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: bucket98/locust:system-v1
        command: ["locust", "-f", "locustfile.py", "--master", "-H", "http://backend:8080"]
        ports:
        - containerPort: 8089
        - containerPort: 5557
